config/routes.rb
Rails.application.routes.draw do
  get 'karte/index'
  post 'karte/index'

  resources :leagues, only: [:index, :create]

  get 'leagues/index'

  get 'welcome/index'

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/birthplace.rb
class Birthplace < ApplicationRecord
end

app/models/goal.rb
# Goal-Model holds information about goals shot in a match
class Goal < ApplicationRecord
  self.primary_key = 'goal_id'
  belongs_to :match
  has_many :leagues, through: :league_goals, dependent: :destroy
end

app/models/goalgetter.rb
class Goalgetter < ApplicationRecord
end

app/models/group.rb
# Group-Model holds information about 'Spieltag'
class Group < ApplicationRecord
  self.primary_key = 'group_id'
  has_many :matches, dependent: :destroy, foreign_key: 'match_id', primary_key: 'match_id'
end

app/models/league.rb
# League-Model holds information about
class League < ApplicationRecord
  self.primary_key = 'league_id'
  has_many :matches, dependent: :destroy, foreign_key: 'match_id', primary_key: 'match_id'
  has_many :goals, through: :league_goals, dependent: :destroy
end

app/models/league_goal.rb
class LeagueGoal < ApplicationRecord
  belongs_to :league
  belongs_to :goal
end

app/models/match.rb
# Match-Model holds information about a certain match in a given group and league
class Match < ApplicationRecord
  self.primary_key = 'match_id'
  belongs_to :league
  belongs_to :group

  has_many :match_results, dependent: :destroy, foreign_key: 'result_id', primary_key: 'result_id'
  has_many :goals, dependent: :destroy, foreign_key: 'goal_id', primary_key: 'goal_id'
end

app/models/match_result.rb
class MatchResult < ApplicationRecord
  self.primary_key = 'result_id'
  belongs_to :match
end

app/models/team.rb
class Team < ApplicationRecord
  self.primary_key = 'team_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/karte_controller.rb
class KarteController < ApplicationController
  def index
    @league_shortcut = params[:league_shortcut]
    puts 'karte hat league_shortcut: ' + @league_shortcut
  end
  def getNbOfGoalsPerEntity(season, group_id, entity_wiki_id)
    #ToDo fertig schreiben /testen
    #returns the number of Goals on this matchday scored from players born in the entity
    count = 0
    matches = Match.where(group_id: group_id)
    for match in matches do
      goals = Goal.where(match_id:match.match_id )
      for goal in goals do
        #those are the goals scored on that matchday
        # diese Abfrage wirkt ziemlich zeitintensiv, wie kann man sie scheller machen?
        goalgetter = Goalgetter.where(goalgetter_id: goal.goalgetter_id )
        if not goalgetter == nil
         if checkHigherDistricts?(goalgetter.birthplace_id, entity_wiki_id)
           count += 1
         end
      end
    end
  end
  end

  def checkHigherDistricts?(wiki_id_higherDistrict, wiki_id_compareWith )
    if wiki_id_higherDistrict == wiki_id_compareWith
      return true
    end
    if not Birthplace.exists?(wiki_id:wiki_id_higherDistrict)
      return false
    end
    higher_district = Birthplace.where(wiki_id: wiki_id_higherDistrict).first

      puts higher_district.wiki_id
      puts higher_district.to_s
      return  checkHigherDistricts?( higher_district.district_wiki_id, wiki_id_compareWith)


  end
  end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  def index
    begin
      @openligaReachable = true
      @sports_id = params[:sports_id]
      @sports_name = params[:sports_name]
      # get available online data
      response = OpenligaSoapService.new.get_avail_leagues_by_sports(@sports_id)
      @avail_leagues_online = response.sort_by { |hash| hash[:league_saison] }
      @league_goals = LeagueGoal.all
      # get available local data
    rescue => error
      puts 'LeaguesController - Error: ' + error.message.to_s
      @openligaReachable = false
      @avail_leagues_local = League.where(sports_id: params[:sports_id])
      @league_goals = LeagueGoal.all
    end
  end

  def create
    OpenligaParser.new.parse_openliga(params[:sports_id],
                                      params[:sports_name],
                                      params[:league_shortcut],
                                      params[:league_saison])
    redirect_to action: 'index', sports_id: params[:sports_id]
  end

  private
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    begin
      @openligaReachable = true
      @avail_sports_online = OpenligaSoapService.new.get_avail_sports
    rescue => error
      puts 'WelcomeController - Error: ' + error.message.to_s
      @openligaReachable = false
      @avail_sports_local = League.select(:sports_id).distinct
      end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/karte_helper.rb
module KarteHelper
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/karte/index.html.erb
<!DOCTYPE html>

<html lang="de">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Bundesliga</title>
  <script src="http://code.jquery.com/jquery-latest.js"></script>
  <script src="/javascript/jquery.tooltip.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link href="/stylesheet/style.css" rel="stylesheet">
</head>

<body>
<div class="main_container" style="margin-top:150px;">
  <div id="text">
    <h1>Bundesliga</h1>
    <p>Wählen Sie ein Bundesland aus.</p>
    <table id = "landkreise_table">
      <thead>
        <tr>
          <th>
            <select id="filterText_landkreise" style="display: inline-block" >
		    <option value="Sachsen" selected> Sachsen </option>
		    <option value='Baden-Württemberg'>Baden-Württemberg</option>
		    <option value='Bayern'>Bayern</option>
		    <option value='Berlin'>Berlin</option>
		    <option value='Brandenburg'>Brandenburg</option>
		    <option value='Bremen'>Bremen</option>
		    <option value='Hamburg'>Hamburg</option>
		    <option value='Hessen'>Hessen</option>
		    <option value='Mecklenburg-Vorpommern'>Mecklenburg-Vorpommern</option>
		    <option value='Niedersachsen'>Niedersachsen</option>
		    <option value='Nordrhein-Westfalen'>Nordrhein-Westfalen</option>
		    <option value='Rheinland-Pfalz'>Rheinland-Pfalz</option>
               <option value='Saarland'>Saarland</option>
               <option value='Sachsen-Anhalt'>Sachsen-Anhalt</option>
		    <option value='Schleswig-Holstein'>Schleswig-Holstein</option>
		    <option value='Thüringen'> Thüringen</option>
		    <option value='alle'>Alle</option>
             </select>
          </th>
          <th data-type="number">Tore<input type="radio" id="tore_switch_landkreise"  name="tabledata_landkreise">Zeigen</th>
          <th data-type="number">Rote Karten<input type="radio" id="rote_karten_switch_landkreise" name="tabledata_landkreise"><label for="peopleswitch">Zeigen</label></th>
          <th data-type="number">Gelbe Karten<input type="radio" id="gelbe_karten_switch_landkreise" name="tabledata_landkreise">Zeigen</th>
      </tr>
      </thead>
      <tbody>
      <tr id='sachsen_'>
        <td>Bautzen</td>
        <td>185</td>
        <td>30</td>
        <td>57</td>
      </tr>
      <tr id='sachsen_'>
        <td>Chemnitz</td>
        <td>174</td>
        <td>39</td>
        <td>67</td>
      </tr>
      <tr id='sachsen_'>
        <td>Dresden</td>
        <td>164</td>
        <td>54</td>
        <td>78</td>
      </tr>
      <tr id='sachsen_'>
        <td>Erzgebirgskreis</td>
        <td>134</td>
        <td>45</td>
        <td>57</td>
      </tr>
      <tr id='sachsen_'>
        <td>Görlitz</td>
        <td>193</td>
        <td>67</td>
        <td>58</td>
      </tr>
      <tr id='sachsen_'>
        <td>Leipzig-Stadt</td>
        <td>67</td>
        <td>65</td>
        <td>39</td>
      </tr>
      <tr id='sachsen_'>
        <td>Leipzig-Landkreis</td>
        <td>86</td>
        <td>48</td>
        <td>87</td>
      </tr>
      <tr id='sachsen_'>
        <td>Mittelsachsen</td>
        <td>137</td>
        <td>67</td>
        <td>73</td>
      </tr>
      <tr id='sachsen_'>
        <td>Nordsachsen</td>
        <td>121</td>
        <td>105</td>
        <td>86</td>
      </tr>
      <tr id='sachsen_'>
        <td>Sächsische Schweiz-Osterzgebirge</td>
        <td>54</td>
        <td>76</td>
        <td>33</td>
      </tr>
      <tr id='sachsen_'>
        <td>Vogtlandkreis</td>
        <td>85</td>
        <td>64</td>
        <td>87</td>
      </tr>
      <tr id='sachsen_'>
        <td>Zwickau</td>
        <td>78</td>
        <td>39</td>
        <td>87</td>
      </tr>
      </tbody>
    </table>


    <table id="lands" class="">
      <thead>
      <tr>
        <th>
          <select id="filterText" style="display:inline-block" onmousedown="this.value='';" onchange="myFunction(this.value)">
            <option disabled selected>Bundesland</option>
            <option value='Baden-Württemberg'>Baden-Württemberg</option>
            <option value='Bayern'>Bayern</option>
            <option value='Berlin'>Berlin</option>
            <option value='Brandenburg'>Brandenburg</option>
            <option value='Bremen'>Bremen</option>
            <option value='Hamburg'>Hamburg</option>
            <option value='Hessen'>Hessen</option>
            <option value='Mecklenburg-Vorpommern'>Mecklenburg-Vorpommern</option>
            <option value='Niedersachsen'>Niedersachsen</option>
            <option value='Nordrhein-Westfalen'>Nordrhein-Westfalen</option>
            <option value='Rheinland-Pfalz'>Rheinland-Pfalz</option>
            <option value='Saarland'>Saarland</option>
            <option value='Sachsen'>Sachsen</option>
            <option value='Sachsen-Anhalt'>Sachsen-Anhalt</option>
            <option value='Schleswig-Holstein'>Schleswig-Holstein</option>
            <option value='Thüringen'> Thüringen</option>
            <option value='alle'>Alle</option>
          </select>
        </th>
        <th data-type="number">Tore<input type="radio" id="tore_switch"  name="tabledata">Zeigen</th>
        <th data-type="number">Rote Karten<input type="radio" id="rote_karten_switch" name="tabledata"><label for="peopleswitch">Zeigen</label></th>
        <th data-type="number">Gelbe Karten<input type="radio" id="gelbe_karten_switch" name="tabledata">Zeigen</th>
      </tr>
      </thead>
      <tbody>
      <tr id='DE-BW'>
        <td>Baden-Württemberg</td>
        <td>185</td>
        <td>30</td>
        <td>57</td>
      </tr>
      <tr id='DE-BY'>
        <td>Bayern</td>
        <td>170</td>
        <td>29</td>
        <td>64</td>
      </tr>
      <tr id='DE-BE'>
        <td>Berlin</td>
        <td>130</td>
        <td>20</td>
        <td>61</td>
      </tr>
      <tr id='DE-BB'>
        <td>Brandenburg</td>
        <td>98</td>
        <td>36</td>
        <td>54</td>
      </tr>
      <tr id='DE-HB'>
        <td>Bremen</td>
        <td>65</td>
        <td>21</td>
        <td>76</td>
      </tr>
      <tr id='DE-HH'>
        <td>Hamburg</td>
        <td>73</td>
        <td>89</td>
        <td>43</td>
      </tr>
      <tr id='DE-HE'>
        <td>Hessen</td>
        <td>82</td>
        <td>39</td>
        <td>68</td>
      </tr>
      <tr id='DE-MV'>
        <td>Mecklenburg-Vorpommern</td>
        <td>97</td>
        <td>18</td>
        <td>130</td>
      </tr>
      <tr id='DE-NI'>
        <td>Niedersachsen</td>
        <td>76</td>
        <td>58</td>
        <td>114</td>
      </tr>
      <tr id='DE-NW'>
        <td>Nordrhein-Westfalen</td>
        <td>47</td>
        <td>67</td>
        <td>132</td>
      </tr>
      <tr id='DE-RP'>
        <td>Rheinland-Pfalz</td>
        <td>89</td>
        <td>44</td>
        <td>111</td>
      </tr>
      <tr id='DE-SL'>
        <td>Saarland</td>
        <td>60</td>
        <td>118</td>
        <td>18</td>
      <tr id='DE-SN'>
        <td>Sachsen</td>
        <td>77</td>
        <td>134</td>
        <td>104</td>
      </tr>
      <tr id='DE-ST'>
        <td>Sachsen-Anhalt</td>
        <td>49</td>
        <td>143</td>
        <td>44</td>
      </tr>
      <tr id='DE-SH'>
        <td>Schleswig-Holstein</td>
        <td>152</td>
        <td>86</td>
        <td>27</td>
      </tr>
      <tr id='DE-TH'>
        <td>Thüringen</td>
        <td>94</td>
        <td>47</td>
        <td>43</td>
      </tr>

      </tbody>
    </table>
    <br>
    <input id="show_land_kreise" type="radio" name="land_data"> Landkreise<br>
    <input id="show_bundeslander" type="radio" name="land_data" checked disabled> Bundeslander<br>
  </div>
  <figure id="figure_bundesland">
    <object data="/images/germanyHigh.svg" type="image/svg+xml" id="bundesland">
      <p>Sie benutzen alte Brauser Version</p>
    </object>
    <figcaption></figcaption>
  </figure>
  <figure id="figure_landkreise">
    <object data="/images/germanyLandkreise.svg" type="image/svg+xml" id="landkreise">
      <p>Sie benutzen alte Brauser Version</p>
    </object>
  </figure>

</div>
<script src="/javascript/kreis_table_sorting.js"></script>
<script  src="/javascript/main_script.js"></script>
<script  src="/javascript/land_table_sorting.js"></script>


</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WCMBundesliga</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/leagues/index.html.erb
<% if @openligaReachable %>
    <h1>Dafür gibt es u.a. folgende Ligen auf openliga.db:</h1>
    <table id="leagues_leagues-table_online">
      <tr>
        <th>Liga-Id</th>
        <th>Liga-Name</th>
        <th>Saison</th>
        <th>geschossene Tore</th>
      </tr>

      <% @avail_leagues_online.each do |l| %>
          <% if l[:league_shortcut] == 'bl1' %>
              <tr>
                <td><%= l[:league_id] %></td>
                <td><%= l[:league_name] %></td>
                <td><%= l[:league_saison] %></td>
                <% if League.exists?(league_id: l[:league_id]) %>
                    <td>
                      <%= @league_goals.select('goal_id').where(league_id: l[:league_id]).count %>
                    </td>
                    <td><%= button_to 'zur Karte', controller: 'karte',
                                      :league_shortcut => l[:league_shortcut],
                                      :league_saison => l[:league_saison] %>
                    </td>
                <% else %>
                    <td> n.a. </td>
                    <td><%= button_to 'Laden', action: 'create',
                                      :sports_id => @sports_id,
                                      :sports_name => @sports_name,
                                      :league_shortcut => l[:league_shortcut],
                                      :league_saison => l[:league_saison] %>
                    </td>
                <% end %>
              </tr>
          <% end %>
      <% end %>
    </table>

    <p>
      <%= link_to 'zurück zur Sport-Auswahl' , welcome_index_path %>
    </p>
<% else %>
    <h2>Leider ist unsere Online-Ressouce im Moment nicht erreichbar. Diese Daten stehen lokal zur Verfügung:</h2>
    <table id="leagues_leagues-table_local">
      <tr>
        <th>Liga-Id</th>
        <th>Liga-Name</th>
        <th>Saison</th>
        <th>geschossene Tore</th>
      </tr>

      <% @avail_leagues_local.each do |l| %>
          <% if l[:league_shortcut] == 'bl1' %>
              <tr>
                <td><%= l[:league_id] %></td>
                <td><%= l[:league_name] %></td>
                <td><%= l[:league_saison] %></td>
                <% if League.exists?(league_id: l[:league_id]) %>
                    <td>
                      <%= @league_goals.select('goal_id').where(league_id: l[:league_id]).count %>
                    </td>
                    <td><%= button_to 'zur Karte', controller: 'karte',
                                      :league_shortcut => l[:league_shortcut],
                                      :league_saison => l[:league_saison] %>
                    </td>
                <% else %>
                    <td> n.a. </td>
                    <td><%= button_to 'Laden', action: 'create',
                                      :sports_id => @sports_id,
                                      :sports_name => @sports_name,
                                      :league_shortcut => l[:league_shortcut],
                                      :league_saison => l[:league_saison] %>
                    </td>
                <% end %>
              </tr>
          <% end %>
      <% end %>
    </table>

    <p>
      <%= link_to 'zurück zur Sport-Auswahl' , welcome_index_path %>
    </p>
<% end %>

app/views/welcome/index.html.erb
<h1>Wissens- und Content-Management</h1>

<% if @openligaReachable %>
    <h2>Wähle die gewünschte Sportart (Quelle: www.openligadb.de)</h2>
    <table id="welcome_sports-table_online">
      <tr>
        <th>Sport-ID</th>
        <th>Bezeichnung</th>
      </tr>
      <% @avail_sports_online.each do |s| %>
          <tr>
            <td><%= s[:sports_id] %></td>
            <td>
              <% if s[:sports_id] == 1.to_s %>
                  <%= link_to s[:sports_name].to_s, {:controller => 'leagues',
                                                     :sports_id => s[:sports_id],
                                                     :sports_name => s[:sports_name]} %>
              <% else %>
                  <%= s[:sports_name] %>
              <% end %>
            </td>
          </tr>
      <% end %>
    </table>
<% else %>
    <h2>Leider ist unsere Online-Ressouce www.openligadb.de im Moment nicht erreichbar.
      Prüfe ggf. deine Netzwerkverbindung. Folgende Daten sind lokal verfügbar:</h2>
    <table id="welcome_sports-table_local">
      <tr>
        <th>Sport-ID</th>
      </tr>
      <% @avail_sports_local.each do |s| %>
          <tr>
            <td>
              <% if s[:sports_id] == 1 %>
                  <%= link_to s[:sports_id].to_s + ' - Fußball', {:controller => 'leagues',
                                                     :sports_id => s[:sports_id]} %>
              <% else %>
                  <%= s[:sports_id] %>
              <% end %>
            </td>
          </tr>
      <% end %>
    </table>
<% end %>